# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ff1968a2536738224b8c443adbdbf79fd930fed1d042e354bd1eb0cf49ea5801a031ce6f76372e32d931ab60cb88d37efad0b757a436842fe19e0b50d0a9118

test:
  secret_key_base: 286c53eb6b28a54eaf21bc37634673e761eba134fadeb93807f3d543ff87416daa8275f3818f5de2e07b6ff9655eb1f99c593c869dd02f6863fc91cb04524f17

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
